streamlining workflow

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -12,8 +12,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-    - name: installing prequesites
-      run: sudo apt install make && sudo apt install clang
-    - name: make build
-      run: make build
+    - name: Install prerequisites
+      run: sudo apt-get update && sudo apt-get install -y build-essential clang make
+    - name: Build project
+      run: |
+        if ! make build; then
+          echo "Build failed"
+          exit 1
+        fi
+    - uses: actions/upload-artifact@v4
+      with:
+        name: simplemath
+        path: simplemath
